name: bento_box_library
description: A versatile Flutter library offering customizable Bento-style widgets for creating modular, responsive, and visually appealing UI components.
version: 1.1.3
homepage: https://github.com/SxryxnshS5/bento_box_library

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/screenshot.png
